sudo: required

services:
 - docker

language: go

# Versions of go that are explicitly supported by gonum.
go:
 - 1.4.2
 - 1.5.3
 - 1.6

env:
  matrix:
  - BLAS_LIB=OpenBLAS
  - BLAS_LIB=gonum
  # Does not currently link correctly.  Note that there is an issue with drotgm in ATLAS.
  # - BLAS_LIB=ATLAS
  # If we can get multiarch builds on travis.
  # There are some issues with the Accellerate implementation.
  #- BLAS_LIB=Accellerate

# Install the appropriate blas library (if any) and associated gonum software.
install:
 - source  ${TRAVIS_BUILD_DIR}/.travis/$TRAVIS_OS_NAME/$BLAS_LIB/install.sh

script:
 - source  ${TRAVIS_BUILD_DIR}/.travis/$TRAVIS_OS_NAME/$BLAS_LIB/test.sh
 - diff <(gofmt -d *.go) <("")
